// <auto-generated />
using System;
using BookDataProvider;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BookDataProvider.Migrations
{
    [DbContext(typeof(BookDBContext))]
    [Migration("20181214105758_book8")]
    partial class book8
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BookDataProvider.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddedAt");

                    b.Property<string>("AuthorFullName");

                    b.Property<string>("AuthorShortName");

                    b.Property<int?>("CategoryId");

                    b.Property<DateTime>("DateAddedToStore");

                    b.Property<string>("Description");

                    b.Property<string>("ImageURL");

                    b.Property<string>("Isbn");

                    b.Property<int>("PagesAmnt");

                    b.Property<string>("Publisher");

                    b.Property<int>("RunAmnt");

                    b.Property<string>("Series");

                    b.Property<string>("StoreCode");

                    b.Property<string>("Subcategory");

                    b.Property<string>("Target");

                    b.Property<string>("Title");

                    b.Property<string>("Translated");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<int>("Year");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("BookDataProvider.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("BookDataProvider.Entities.JobLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BooksFetched");

                    b.Property<DateTime?>("CompletedAt");

                    b.Property<string>("ExceptonMessage");

                    b.Property<string>("ExceptonStacktrace");

                    b.Property<DateTime?>("FailedAt");

                    b.Property<DateTime>("StartedAt");

                    b.HasKey("Id");

                    b.ToTable("JobLog");
                });

            modelBuilder.Entity("BookDataProvider.Entities.Book", b =>
                {
                    b.HasOne("BookDataProvider.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");
                });
#pragma warning restore 612, 618
        }
    }
}
